title: [Mein Tagesbuch](https://akoezeibrahi.github.io/Blogbeitraege_BAIN20_Akoezel/)
author: Ibrahim
email: ibrahim.akoezel@stud.fhgr.ch
description: > # this means to ignore newlines until "baseurl:"
  Beitärge für mein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik vom FS2020

github_username:  akoezeibrahi

show_excerpts: true # set to false to remove excerpts on the homepage


theme: jekyll-theme-merlot
